version: "3.9"

services:
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning

  backend:
    build: .
    container_name: backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./core:/app
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=test
      - DEBUG=True
    depends_on:
      - redis

  worker:
    build: .
    command: celery -A core worker --loglevel=info
    volumes:
      - ./core:/app
    depends_on:
      - redis
      - backend
  
  smtp4dev:
    image: rnwood/smtp4dev:v3
    restart: always
    ports:
      # Change the number before : to the port the web interface should be accessible on
      # Add 127.0.0.1: prefix for localhost-only access (recommended for security)
      - '5000:80'
      # Change the number before : to the port the SMTP server should be accessible on
      # Add 127.0.0.1: prefix for localhost-only access (recommended for security)
      - '25:25'
      # Change the number before : to the port the IMAP server should be accessible on
      # Add 127.0.0.1: prefix for localhost-only access (recommended for security)
      - '143:143'
      # Change the number before : to the port the POP3 server should be accessible on
      # Add 127.0.0.1: prefix for localhost-only access (recommended for security)
      - '110:110'
    volumes:
        - smtp4dev-data:/smtp4dev
    environment:
      - ServerOptions__Urls=http://*:80
      - ServerOptions__HostName=smtp4dev

  # master:
  #   image: locustio/locust
  #   ports:
  #    - "8089:8089"
  #   volumes:
  #     - ./core/locust:/mnt/locust
  #   command: -f /mnt/locust/locustfile.py --master -H http://backend:8000
  
  # worker:
  #   image: locustio/locust
  #   volumes:
  #     - ./core/locust:/mnt/locust
  #   command: -f /mnt/locust/locustfile.py --worker --master-host master

volumes:
  smtp4dev-data: